baseURL: "https://suatkarakusoglu.github.io/"
title: Suat K. 
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
        - name: Archive 
          url: archive
          weight: 5
        - name: Categories
          url: categories
          weight: 10
        - name: Search
          url: search
          weight: 10
          
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "iOS, Flutter, emacs..."
    author: Suat K. 
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    # comments: false
    # images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Suat Karakusoglu
        # imageUrl: "#"
        # imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "Hokus Pokus"
        buttons:
            - name: Archive 
              url: archive 
            - name: Categories 
              url: categories 
            - name: About 
              url: about 

    homeInfoParams:
        Title: "Suat K."
        Content: >
            Welcome to site. 

    socialIcons:
        - name: github
          url: "https://github.com/suatkarakusoglu"
        - name: stackoverflow 
          url: "https://stackoverflow.com/users/837222/suat-karakusoglu"
        - name: RsS
          url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
# assets: #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

# privacy:
#     vimeo:
#         disabled: false
#         simple: true

#     twitter:
#         disabled: false
#         enableDNT: true
#         simple: true

#     instagram:
#         disabled: false
#         simple: true

#     youtube:
#         disabled: false
#         privacyEnhanced: true

# services:
#     instagram:
#         disableInlineCSS: true
#     twitter:
#         disableInlineCSS: true
