baseurl = "https://suatkarakusoglu.github.io/"
title = "STKRKSGL"

languageCode = "en-us"
disqusShortname = "suatkarakusoglu"
MetaDataFormat = "toml"

theme = "HugoInk"
paginate = 30

[outputs]
    home = ["HTML", "JSON"]

[author]
    name = "Suat Karakusoglu"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "tango"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

# All parameters below here are optional and can be mixed and matched.
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Emacs, iOS, Flutter, coding and more."
    defaultKeywords = "Emacs, iOS, Flutter, C++, Python"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Juggling..."

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/suatkarakusoglu"
    bitbucket = ""
    stackOverflow = "https://stackoverflow.com/users/837222/suat-karakusoglu"
    linkedin = "https://www.linkedin.com/in/suat-karakusoglu/"
    twitter = "https://twitter.com/suatkarakusoglu"
    youtube = ""

    # Mailto link.
    email = "mailto:suatkarakusoglu@gmail.com"

    # GPG key.
    # gpgkey = "/gpg_public_key.txt"

    # RSS.
    rss = false

    # Privacy statement link.
    # privacyPolicy = ""

[[menu.main]]
    url = "/emacs/index.html"
    name = "Emacs"
    weight = 2

[[menu.main]]
    url = "/iOS/index.html"
    name = "IOS"
    weight = 3

[[menu.main]]
    url = "/flutter/index.html"
    name = "Flutter"
    weight = 4